routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.home');
})->name('home');

Route::namespace('AdminAuth')->group(function (){
    Route::prefix('users')->group(function (){
        Route::resource('wda', "WdaController");
        Route::resource('rp', "RpController");
        Route::resource('college', "CollegeController");
        Route::resource('school', "SchoolsController");
        Route::resource('examiner', "ExaminerController");
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/', "HomeController@view")->name('verify');
Route::match(['GET', 'POST'], '/schools/{slugname?}', ['as' => 'home.schools', 'uses' => 'HomeController@schools']);
Route::get('/schoolsmap', ['as' => 'home.schools.map', 'uses' => 'HomeController@schoolsmap']);
Route::match(['POST'], '/findaschool', ['as' => 'home.schools.findaschool', 'uses' => 'HomeController@findaschool']);
Route::post('/sendmessage', ['as' => 'home.schools.sendmessage', 'uses' => 'HomeController@sendmessage']);

//Contact Us

Route::get('/request-account', "HomeController@requestAccount")->name('school.request.account');
Route::post('/request-account', "HomeController@requestAccount")->name('school.request.account');
Route::get('/contact-us', "HomeController@contactUs")->name('contact.us');
Route::post('/contact-us', "HomeController@contactUs")->name('contact.us');;

Route::group(['prefix' => 'school'], function () {
    Route::get('/login', 'SchoolAuth\LoginController@showLoginForm')->name('school.login');
    Route::post('/login', 'SchoolAuth\LoginController@login');
    Route::post('/logout', 'SchoolAuth\LoginController@logout')->name('school.logout');

//  Route::get('/register', 'SchoolAuth\RegisterController@showRegistrationForm')->name('school.register');
//  Route::post('/register', 'SchoolAuth\RegisterController@register');

    Route::post('/password/email', 'SchoolAuth\ForgotPasswordController@sendResetLinkEmail')->name('school.password.request');
    Route::post('/password/reset', 'SchoolAuth\ResetPasswordController@reset')->name('school.password.email');
    Route::get('/password/reset', 'SchoolAuth\ForgotPasswordController@showLinkRequestForm')->name('school.password.reset');
    Route::get('/password/reset/{token}', 'SchoolAuth\ResetPasswordController@showResetForm');
});

Route::get('/dashboard', 'HomeController@dashboard')->name('home.dashboard');
Route::get('/attachments', 'HomeController@attachments')->name('home.attachments');

Route::group(['prefix' => 'student'], function () {
    Route::get('/login', 'StudentAuth\LoginController@showLoginForm')->name('student.login');
    Route::post('/login', 'StudentAuth\LoginController@login');
    Route::post('/logout', 'StudentAuth\LoginController@logout')->name('student.logout');

//  Route::get('/register', 'StudentAuth\RegisterController@showRegistrationForm')->name('student.register');
//    Route::post('/register', 'StudentAuth\RegisterController@register');

    Route::get('/signup/private', "StudentAuth\SignupsController@private")->name('student.signup.private');
    Route::get('/signup/continuing', "StudentAuth\SignupsController@continuing")->name('student.signup.continuing');

    Route::post('/signup/private', "StudentAuth\SignupsController@postPrivate")->name('student.post.signup.private');
    Route::post('/signup/continuing', "StudentAuth\SignupsController@poastContinuing")->name('student.post.signup.continuing');

    Route::post('/password/email', 'StudentAuth\ForgotPasswordController@sendResetLinkEmail')->name('student.password.request');
    Route::post('/password/reset', 'StudentAuth\ResetPasswordController@reset')->name('student.password.email');
    Route::get('/password/reset', 'StudentAuth\ForgotPasswordController@showLinkRequestForm')->name('student.password.reset');
    Route::get('/password/reset/{token}', 'StudentAuth\ResetPasswordController@showResetForm');
});

Route::get("/location/{where}/{value}", "ToAllController@getlocation")->name('boundary');
Route::get("/filter-location/{where}/{value}", "ToAllController@getFilterlocation")->name('boundaryFilter');
//Route::get("/location/{where}/{value}", "HomeController@getlocation")->name('boundary');
Route::get("/poly/{where}/{value}", "HomeController@ajaxGetSchools")->name("schooling");
Route::get("/poly/{where}/{col}/{value}", "HomeController@ajaxGetSchools")->name("schooling");

Route::get('/get/subsectors/{sector_id}', 'HomeController@getSubSectors');
Route::get('/get/currqualifications/{sub_sector_id}', 'HomeController@getCurrQualifications');

Route::get('/api/programs/c/{college_id}/d/{department_id}', 'HomeController@getPrograms');
Route::get('/api/programs/c/{college_id}', 'HomeController@getPrograms');

Route::group(['prefix' => 'admin'], function () {
    //Voyager::routes();
});

Route::group(['prefix' => 'reb'], function () {
    Route::get('/login', 'RebAuth\LoginController@showLoginForm')->name('reb.login');
    Route::post('/login', 'RebAuth\LoginController@login');
    Route::post('/logout', 'RebAuth\LoginController@logout')->name('logout');

    Route::get('/register', 'RebAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'RebAuth\RegisterController@register');
    Route::get('/register/verify', 'RebAuth\RegisterController@verify')->name('verifyEmailLink');
    Route::get('/register/verify/resend', 'RebAuth\RegisterController@showResendVerificationEmailForm')->name('showResendVerificationEmailForm');
    Route::post('/register/verify/resend', 'RebAuth\RegisterController@resendVerificationEmail')->name('resendVerificationEmail');

    Route::post('/password/email', 'RebAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'RebAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'RebAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'RebAuth\ResetPasswordController@showResetForm');

});

Route::group(['prefix' => 'examiner'], function () {
    Route::get('/login', 'ExaminerAuth\LoginController@showLoginForm')->name('examiner.login');
    Route::post('/login', 'ExaminerAuth\LoginController@login');
    Route::post('/logout', 'ExaminerAuth\LoginController@logout')->name('logout');

//    Route::get('/register', 'ExaminerAuth\RegisterController@showRegistrationForm')->name('register');
    Route::group(['middleware' => ['admin']], function () {
        Route::post('/register', 'ExaminerAuth\RegisterController@register')->name('register.examiner');
    });

    Route::post('/password/email', 'ExaminerAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'ExaminerAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'ExaminerAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'ExaminerAuth\ResetPasswordController@showResetForm');
});


Route::group(['prefix' => 'wda'], function () {
    Route::get('/login', 'WdaAuth\LoginController@showLoginForm')->name('wda.login');
    Route::post('/login', 'WdaAuth\LoginController@login');
    Route::post('/logout', 'WdaAuth\LoginController@logout')->name('logout');

//    Route::get('/register', 'WdaAuth\RegisterController@showRegistrationForm')->name('register');
    Route::group(['middleware' => ['admin']], function () {
        Route::post('/register', 'WdaAuth\RegisterController@register')->name('register.wda');
    });

    Route::post('/password/email', 'WdaAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'WdaAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'WdaAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'WdaAuth\ResetPasswordController@showResetForm');
    
});

/**
 *** Curricula Guidance
 **** View Curricula
 */

Route::prefix('curriculum')->group(function () {
    Route::get('/', 'CurriculumController@view')->name('curricula.index');
    Route::get('/trades/{id}', 'CurriculumController@tradesView')->name('curricula.view.trades');
    Route::get('/{id}/view', 'CurriculumController@curriculumView')->name('curriculum.view');
    Route::post('/{id}/except', 'CurriculumController@view');
    Route::get('/{id}/{trade}', 'CurriculumController@view')->name('curricula.view');
});

Route::group(['prefix' => 'rp'], function () {
    Route::get('/login', 'RpAuth\LoginController@showLoginForm')->name('rp.login');
    Route::post('/login', 'RpAuth\LoginController@login');
    Route::post('/logout', 'RpAuth\LoginController@logout')->name('logout');

//  Route::get('/register', 'RpAuth\RegisterController@showRegistrationForm')->name('register');
    Route::group(['middleware' => ['admin_and_rp']], function () {
        Route::post('/register', 'RpAuth\RegisterController@register')->name('register.rp');
    });

    Route::post('/password/email', 'RpAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'RpAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'RpAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'RpAuth\ResetPasswordController@showResetForm');
});

Route::group(['prefix' => 'college'], function () {
    Route::get('/login', 'CollegeAuth\LoginController@showLoginForm')->name('college.login');
    Route::post('/login', 'CollegeAuth\LoginController@login');
    Route::post('/logout', 'CollegeAuth\LoginController@logout')->name('logout');

//  Route::get('/register', 'CollegeAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'CollegeAuth\RegisterController@register');

app/Reb.php
<?php

namespace App;

use App\Notifications\RebResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Reb extends Authenticatable /*implements CanVerifyEmailContract*/
{
    protected $connection = 'mysql';

    use Notifiable;

    /*use CanVerifyEmail;*/

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new RebResetPassword($token));
    }

    public function attachement()
    {
        return $this->hasMany(RebStaffProfileAttachmentsFinal::class, 'staff_id', 'id');
    }

    public function markingApplications()
    {
        return $this->hasMany(RebStaffMarkerApplication::class, 'staff_id', 'id');
    }

    public function getCurrentMarkingAttribute()
    {
        if ($this->markingApplications->count() > 0) {
            $ch = $this->markingApplications()->where('academic_year', date('Y'))->first();
            if ($ch)
                return $ch;
        }

        return false;
    }

    public function getSchoolNameAttribute()
    {
        if ($this->school)
            return $this->school;

        return "";

    }

    public function getSchoolAcronymAttribute()
    {
        if ($this->school)
            return $this->school;

        return "";

    }

    public function markingBackgrounds()
    {
        return $this->hasMany(RebStaffMarkingBackground::class, 'staff_id', 'id');
    }

    public function teachingExperience()
    {
        return $this->hasMany(RebStaffTeachingExperience::class, 'staff_id', 'id');
    }

    public function workingExperience()
    {
        return $this->hasMany(RebStaffWorkexperience::class, 'staff_id', 'id');
    }

}

app/Http/Controllers/AdminAuth/SchoolsController.php
<?php

namespace App\Http\Controllers\AdminAuth;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SchoolsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/DistrictAuth/SchoolController.php
<?php

namespace App\Http\Controllers\DistrictAuth;

use App\Model\Accr\SchoolInformation;
use App\Model\Accr\SourceSchoolOwnership;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SchoolController extends Controller
{
    private $user;

    public function __construct()
    {
        $this->user = Auth::guard('district')->user();
    }

    public function view()
    {
        $ownerships = SourceSchoolOwnership::all();
        $schools = SchoolInformation::all();

        return view('district.schools.view', compact('schools', 'ownerships'));
    }

    public function internet()
    {
        $ownerships = SourceSchoolOwnership::all();
        $schools = SchoolInformation::where('has_internet', 2)->get();

        return view('district.schools.view', compact('schools', 'ownerships'));
    }

    public function electricity()
    {
        $ownerships = SourceSchoolOwnership::all();
        $schools = SchoolInformation::where('has_electricity', 2)->get();

        return view('district.schools.view', compact('schools', 'ownerships'));
    }

    public function water()
    {
        $ownerships = SourceSchoolOwnership::all();
        $schools = SchoolInformation::where('has_water', 2)->get();

        return view('district.schools.view', compact('schools', 'ownerships'));
    }

    public function viewDetails($id)
    {
        $school = SchoolInformation::find($id);
        return view('district.schools.viewDetails', compact('school'));
    }
}

resources/views/school/requests/create.blade.php
@extends('school.requests.layout.main')

@section('l-style')
    @parent
    <link rel="stylesheet" href="{{ asset('js/jQuery.filer/css/jquery.filer.css') }}">
    <style>
        .jFiler-theme-default .jFiler-input {
            width: inherit !important;
        }
    </style>
@overwrite

@section('box-title')
    <span>Requests Management</span>
@endsection

@section('box-body')
    <div class="box">
        @if($schoolrequest)
            @php($route = ['school.requests.update', $schoolrequest->id])
            @php($id = "updateSchoolRequests")
        @else
            @php($route = 'school.requests.store')
            @php($id = "createSchoolRequests")
        @endif
        {!! Form::open(['route' => $route, 'files' => true, 'method' => 'post', 'class' => 'form', 'id' => $id]) !!}
            {!! Form::hidden('school_id', school(true)->id) !!}
        @if($schoolrequest)
            @method("PATCH")
            {!! Form::hidden('id', $schoolrequest->id) !!}
        @endif
        <div class="box-header">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('request_class', "Request Class *") !!}
                        {!! Form::select('request_class', ['Consumables' => 'Consumables', 'Trainers' => 'Trainers','Trainings'=>'Trainings'], $schoolrequest ? $schoolrequest->request_class : null,
                            ['placeholder' => 'Choose a Request Class...', 'class' => 'form-control select2', 'required' => true]) !!}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('required_units', "Required Unit *") !!}
                        {!! Form::text('required_units', $schoolrequest ? $schoolrequest->required_units : "", ['class' => 'form-control']) !!}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="form-group">
                            {!! Form::label('unit_cost', "Unit Cost *") !!}
                            {!! Form::text('unit_cost', $schoolrequest ? $schoolrequest->unit_cost : "", ['class' => 'form-control']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('request_description', "Request Description *") !!}
                        {!! Form::textarea('request_description', $schoolrequest ?$schoolrequest->request_description: "", ['class' => 'form-control', 'rows' => '2']) !!}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="form-group">
                            {!! Form::label('required_by_date', "Required  By Date *") !!}
                            {!! Form::text('required_by_date', $schoolrequest ? $schoolrequest->required_by_date : null, ['class' => 'datepicker form-control']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('request_attachment', "Attachment") !!}
                        {!! Form::file('request_attachment', ['class' => 'filer_docs_input form-control']) !!}
                    </div>
                </div>
            </div>

        </div>
        <div class="box-footer">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-md btn-primary pull-left">
                        {{ $schoolrequest ? "Update Request" : "Send Request" }}
                    </button>
                    <a href="{{ route('school.requests.index') }}"
                       class="btn btn-md btn-warning pull-right">Cancel</a>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
    @include('school.requests.layout.modals.warnings')
@overwrite
@section('l-scripts')
    @parent
    <script>
        $(function () {
            $(".datepicker").datepicker({
                autoclose: true,
                format: "yyyy-mm-dd"
            });
        });
    </script>

    <script src="{{ asset('js/jQuery.filer/js/jquery.filer.js?v='.time()) }}"></script>
    <script src="{{ asset('js/jQuery.filer/js/filer.js?v='.time()) }}"></script>
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    @if($schoolrequest)
        {!! JsValidator::formRequest('App\Http\Requests\UpdateSchoolRequestsRequest', '#updateSchoolRequests'); !!}
    @else
        {!! JsValidator::formRequest('App\Http\Requests\CreateSchoolRequestsRequest', '#createSchoolRequests'); !!}
    @endif
    <script>
        $(function () {
            $(".jFiler-input").attr('data-toggle', "tooltip")
                .attr('data-placement', "top")
                .attr('title', "Allowed formats: docx, xlsx,pdf or ppt");

            $("#qualification").on("change", function () {
                var dep = $(this).val();
                if (dep.length > 0) {
                    $.get("{{ route('school.get.course.levels') }}",
                        {
                            id: dep,
                            where: 'id'
                        }, function (data) {
                            var h = '<option value="" selected disabled>Select ...</option>';
                            $.each(JSON.parse(data), function (index, level) {
                                h += '<option value="' + level.id + '">' + level.name + '</option>';
                            });
                            console.log(data);
                            $("#level_id").html(h);
                        });
                }
            });

            $(".p").change(function () {
                var p = $(this).val();
                $.get("/location/d/" + p, {}, function (data) {
                    var obj = jQuery.parseJSON(data);
                    var html = "<option value='' selected disabled>Select..</option>";
                    $.each(obj, function (key, value) {
                        $.each(value, function (k, v) {
                            html += "<option value='" + v + "'>" + v + "</option>";
                        });
                    });
                    $(".d").html(html);
                });
            });

            $(".d").change(function () {
                var p = $(this).val();
                $.get("/location/s/" + p, {}, function (data) {
                    var obj = jQuery.parseJSON(data);
                    var html = "<option value='' selected disabled>Select..</option>";
                    $.each(obj, function (key, value) {
                        $.each(value, function (k, v) {
                            html += "<option value='" + v + "'>" + v + "</option>";
                        });
                    });
                    $(".s").html(html);
                });
            });

            $(".s").change(function () {
                var p = $(this).val();
                $.get("/location/c/" + p, {}, function (data) {
                    var obj = jQuery.parseJSON(data);
                    var html = "<option value='' selected disabled>Select..</option>";
                    $.each(obj, function (key, value) {
                        $.each(value, function (k, v) {
                            html += "<option value='" + v + "'>" + v + "</option>";
                        });
                    });
                    $(".c").html(html);
                });
            });

            $(".c").change(function () {
                var p = $(this).val();
                $.get("/location/v/" + p, {}, function (data) {
                    var obj = jQuery.parseJSON(data);
                    var html = "<option value='' selected disabled>Select..</option>";
                    $.each(obj, function (key, value) {
                        $.each(value, function (k, v) {
                            html += "<option value='" + v + "'>" + v + "</option>";
                        });
                    });
                    $(".v").html(html);
                });
            });
        });
    </script>
@endsection

resources/views/school/requests/index.blade.php
@extends('school.requests.layout.main')

@section('l-style')
    @parent
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/css/dataTables.material.min.css"/>

@overwrite

@section('box-title')
    <span>Requests Management</span>
@endsection

@section('box-body')
    <div class="box">
        <div class="box-body">
            <table class="table table-striped" id="dataTable">
                <thead>
                <th>Request Class</th>
                <th>Number of Required Units</th>
                <th>unit cost</th>
                <th>Description</th>
                <th>Require by Date</th>
                <th>School Name</th>
                <th>Request Status</th>
                <th>WDA Comment</th>
                <th>Attachment</th>
                <th></th>
                </thead>
                <tbody>
                @if($schoolrequests->count() > 0)
                    @foreach($schoolrequests as $schoolrequest)
                        <tr>
                            <td>
                                {{ $schoolrequest->request_class }}
                            </td>
                            <td>
                                {{ $schoolrequest->required_units }}
                            </td>
                            <td>
                                <h5>
                                    {{ $schoolrequest->unit_cost }}
                                </h5>
                            </td>
                            <td>
                                {{ $schoolrequest->request_description }}
                            </td>
                            <td>
                                {{ $schoolrequest->required_by_date }}
                            </td>
                            <td>
                                {{ $schoolrequest->school->school_name}}
                            </td>
                            <td>
                                {{ $schoolrequest->request_status}}
                            </td>
                            <td>
                                {{ $schoolrequest->wda_comments}}
                            </td>
                            <td>
                                <a href="{{ asset('storage/'.$schoolrequest->request_attachment) }}">View</a>
                            </td>
                            <th>
                                <a href="{{ route('school.requests.edit', $schoolrequest->id) }}" class="btn btn-info btn-sm">Edit</a>
                                <button type="button" data-url="{{ route('school.requests.destroy', $schoolrequest->id) }}"
                                        data-names="{{ $schoolrequest->request_description }}"
                                        class="btn btn-danger btn-sm btn-delete">Delete
                                </button>
                            </th>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
    </div>
    @include('school.students.layout.modals.warnings')
@overwrite

@section('l-scripts')
    @parent
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.16/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $("#dataTable").dataTable({
                "ordering": false
            });
            $(".btn-delete").on("click", function () {
                let url = $(this).data("url");
                let names = $(this).data("names");
                // console.log(names);
                let modalDelete = $("#removeLevel");
                modalDelete.find("form").prop("action", url);
                modalDelete.find(".box-heading .names").html(names);
                modalDelete.modal();
            });
        });
    </script>
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {{--    {!! JsValidator::formRequest('App\Http\Requests\CreateCourseRequest', '#createCourse'); !!}--}}
    {{--{!! JsValidator::formRequest('App\Http\Requests\StoreClassRequest', '#addClass'); !!}--}}
@endsection